on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install minify
        run: sudo apt-get update && sudo apt-get install minify

      - name: build with zola
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          BUILD_ONLY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: fix permissions
        run: sudo chmod -R a+w public/

      - name: minify assets
        run: minify -r -o public/ public/

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true